# Multiple linear Regression

## Importing the libraries

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [28]:
df = pd.read_csv(r"C:\Users\Oulaya\Learning\Datasets\50_Startups.csv")
X = df.drop("Profit", axis=1)
y = df["Profit"]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [32]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

## Encoding categorical data

In [36]:
X_encoded = pd.get_dummies(X, columns= ["State"]).astype(int)
X_encoded.head()

R&D Spend  Administration  Marketing Spend  State_California  \
0     165349          136897           471784                 0   
1     162597          151377           443898                 1   
2     153441          101145           407934                 0   
3     144372          118671           383199                 0   
4     142107           91391           366168                 0   

   State_Florida  State_New York  
0              0               1  
1              0               0  
2              1               0  
3              0               1  
4              1               0

## Splitting the Dataset into the Training set and Test set

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size = 0.2, random_state = 42)

In [41]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

In [47]:
regressor.fit(X_train, y_train)

LinearRegression()

In [49]:
y_predict = regressor.predict(X_test)

In [51]:
y_predict

array([126362.93252171,  84608.52579873,  99677.45007307,  46357.54709785,
       128750.69322711,  50912.79650817, 109741.00850976, 100643.01925189,
        97598.94761148, 113097.03975177])

In [53]:
from sklearn import metrics
print('R²:', metrics.r2_score(y_test, y_predict))

R²: 0.8987245306218798


In [69]:
np.concatenate((y_predict, y_test), axis=0)

array([126362.93252171,  84608.52579873,  99677.45007307,  46357.54709785,
       128750.69322711,  50912.79650817, 109741.00850976, 100643.01925189,
        97598.94761148, 113097.03975177, 134307.35      ,  81005.76      ,
        99937.59      ,  64926.08      , 125370.37      ,  35673.41      ,
       105733.54      , 107404.34      ,  97427.84      , 122776.86      ])

In [71]:
np.hstack((y_predict, y_test))

array([126362.93252171,  84608.52579873,  99677.45007307,  46357.54709785,
       128750.69322711,  50912.79650817, 109741.00850976, 100643.01925189,
        97598.94761148, 113097.03975177, 134307.35      ,  81005.76      ,
        99937.59      ,  64926.08      , 125370.37      ,  35673.41      ,
       105733.54      , 107404.34      ,  97427.84      , 122776.86      ])

In [73]:
y_predict

array([126362.93252171,  84608.52579873,  99677.45007307,  46357.54709785,
       128750.69322711,  50912.79650817, 109741.00850976, 100643.01925189,
        97598.94761148, 113097.03975177])

In [75]:
y_test

13    134307.35
39     81005.76
30     99937.59
45     64926.08
17    125370.37
48     35673.41
26    105733.54
25    107404.34
32     97427.84
19    122776.86
Name: Profit, dtype: float64

In [81]:
type(y_predict)

numpy.ndarray

In [83]:
type(y_test)

pandas.core.series.Series

In [87]:
y_test = y_test.to_numpy()

In [89]:
np.hstack((y_predict, y_test))

array([126362.93252171,  84608.52579873,  99677.45007307,  46357.54709785,
       128750.69322711,  50912.79650817, 109741.00850976, 100643.01925189,
        97598.94761148, 113097.03975177, 134307.35      ,  81005.76      ,
        99937.59      ,  64926.08      , 125370.37      ,  35673.41      ,
       105733.54      , 107404.34      ,  97427.84      , 122776.86      ])

In [91]:
np.vstack((y_predict, y_test))

array([[126362.93252171,  84608.52579873,  99677.45007307,
         46357.54709785, 128750.69322711,  50912.79650817,
        109741.00850976, 100643.01925189,  97598.94761148,
        113097.03975177],
       [134307.35      ,  81005.76      ,  99937.59      ,
         64926.08      , 125370.37      ,  35673.41      ,
        105733.54      , 107404.34      ,  97427.84      ,
        122776.86      ]])

In [93]:
np.concatenate((y_test, y_predict), 1)

AxisError: axis 1 is out of bounds for array of dimension 1